<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class UtilityTagViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_utility_tag_view()
    {
        $response = $this->get('utilities/tags');

        $response->assertStatus(200)->assertViewIs('utility-tag::tags.index');
    }

    public function test_utility_tag_create()
    {
        $response = $this->get('utilities/tags/create');

        $response->assertViewIs('utility-tag::tags.create_edit')->assertStatus(200);
    }

    public function test_utility_tag_bulk_action()
    {
        $response = $this->post('utilities/tags/bulk-action', [
            'action' => 'active',]);

        $response->assertSeeText('message')
            ->assertDontSee('There is no permission update status');
    }
}
